<?php
/**
 * Enqueue scripts and styles.
 *
 * @package Ifende
 */

if ( ! defined( 'ABSPATH' ) ) {
  exit;
}

/**
 * The above-the-fold woff2 files we preload — keep this list short so the
 * browser doesn't fight itself prioritising too many resources.
 *
 * Picked because:
 *   - syne-400  : body copy
 *   - cormorant-garamond-300 : h1 in the hero
 *
 * Other weights/styles arrive as the local fonts.css parses; with same-origin
 * static files they typically land within the font-display:optional window
 * (~100ms) on warm caches.
 *
 * @return string[]
 */
function ifende_critical_font_files() {
  return [
    'syne-400.woff2',
    'cormorant-garamond-300.woff2',
  ];
}

/**
 * Print <link rel="preload" as="font" type="font/woff2" crossorigin> hints
 * for the critical above-the-fold woff2 files. Pairs with the @font-face
 * declarations in assets/css/fonts.css — the preloaded files are the
 * default fonts for body and the hero h1.
 *
 * Hooked at wp_head priority 1 so the hint lands as early as possible
 * (before main.css is parsed).
 */
function ifende_preload_critical_fonts() {
  foreach ( ifende_critical_font_files() as $filename ) {
    printf(
      '<link rel="preload" href="%s" as="font" type="font/woff2" crossorigin="anonymous">' . "\n",
      esc_url( IFENDE_URI . '/assets/fonts/' . $filename )
    );
  }
}
add_action( 'wp_head', 'ifende_preload_critical_fonts', 1 );

/**
 * Enqueue front-end styles and scripts.
 */
function ifende_enqueue() {
  // Self-hosted fonts. assets/css/fonts.css is generated by `make fonts`
  // (see tools/fetch-fonts.py); the woff2 files live in assets/fonts/.
  // Keeping this as a separate stylesheet (rather than inlining) lets the
  // browser cache it independently from main.css when one of them changes.
  wp_enqueue_style(
    'ifende-fonts',
    IFENDE_URI . '/assets/css/fonts.css',
    [],
    IFENDE_VERSION
  );

  // Use minified assets in production, unminified in debug mode.
  $suffix = ( defined( 'WP_DEBUG' ) && WP_DEBUG ) ? '' : '.min';

  // No-flash theme detection — must run synchronously in <head> BEFORE
  // first paint, so the page is never rendered in the wrong color scheme.
  // Loaded as a static asset (instead of an inline <script>) so it works
  // under a strict Content-Security-Policy without needing a nonce.
  wp_enqueue_script( 'ifende-no-flash', IFENDE_URI . '/assets/js/no-flash.js', [], IFENDE_VERSION, false );

  // Main stylesheet. Depends on ifende-fonts so the font @font-face rules
  // are parsed first; main.css references the families by name.
  wp_enqueue_style( 'ifende-main', IFENDE_URI . '/assets/css/main' . $suffix . '.css', [ 'ifende-fonts' ], IFENDE_VERSION );

  // Main script.
  wp_enqueue_script( 'ifende-main', IFENDE_URI . '/assets/js/main' . $suffix . '.js', [], IFENDE_VERSION, true );

  // Localize script data — email NOT exposed directly (security).
  // The JS mailto fallback will use the AJAX endpoint to retrieve it only when needed.
  wp_localize_script( 'ifende-main', 'ifendeData', [
    'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
    'nonce'     => wp_create_nonce( 'ifende_nonce' ),
    'formspree' => get_theme_mod( 'ifende_formspree_id', '' ),
    'web3forms' => get_theme_mod( 'ifende_web3forms_key', '' ),
  ] );
}
add_action( 'wp_enqueue_scripts', 'ifende_enqueue' );
