#!/usr/bin/env python3
"""Fetch and self-host the Google Fonts used by the Ifende theme.

Run via `make fonts`.

What it does:
    1. Downloads the Google Fonts CSS for the families listed in FONT_URL.
    2. Parses out the *latin* subset @font-face rules (other subsets are
       skipped — the theme is English-only and shipping every Cyrillic /
       Vietnamese variant would more than double the bundle for no gain).
    3. Downloads each woff2 file to assets/fonts/{family}-{weight}[-italic].woff2.
       Files that already exist are skipped, so the script is idempotent
       and cheap to re-run.
    4. Emits assets/css/fonts.css with relative @font-face urls and
       font-display:optional (matching the theme's existing loading strategy).

The point of self-hosting:
    - removes the DNS hop + TLS handshake to fonts.googleapis.com / fonts.gstatic.com
      from the LCP critical path,
    - keeps visitor IPs out of Google's logs (GDPR-clean by default), and
    - lets us preload the actual woff2 files instead of just the stylesheet.

If the font set ever changes, edit FONT_URL and re-run `make fonts` —
existing files stay, new ones are downloaded, the CSS is regenerated.
"""

from __future__ import annotations

import os
import re
import sys
import urllib.request

# The Google Fonts URL the theme used to enqueue.
FONT_URL = (
    'https://fonts.googleapis.com/css2'
    '?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;0,700;1,300;1,600'
    '&family=DM+Mono:wght@300;400;500'
    '&family=Syne:wght@400;600;700;800'
    '&display=swap'
)

# Modern UA so Google serves woff2 (the default css2 endpoint serves older
# formats to stale UAs).
UA = (
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
    '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
)

# Match a single @font-face block from the GF CSS, capturing family / style /
# weight / src URL / unicode-range. Greedy on whitespace inside the block,
# anchored to the closing brace so each block is captured independently.
FONT_FACE_RE = re.compile(
    r"@font-face\s*\{[^}]*?"
    r"font-family:\s*'([^']+)'\s*;[^}]*?"
    r"font-style:\s*(\w+)\s*;[^}]*?"
    r"font-weight:\s*(\d+)\s*;[^}]*?"
    r"src:\s*url\((https://fonts\.gstatic\.com/[^)]+)\)\s*format\('woff2'\)\s*;[^}]*?"
    r"unicode-range:\s*([^;]+);[^}]*?"
    r"\}",
    re.DOTALL,
)


def slug(family: str) -> str:
    """Lowercased hyphen-joined family name, e.g. 'Cormorant Garamond' -> 'cormorant-garamond'."""
    return family.lower().replace(' ', '-')


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main(theme_root: str) -> int:
    fonts_dir = os.path.join(theme_root, 'assets', 'fonts')
    css_path = os.path.join(theme_root, 'assets', 'css', 'fonts.css')
    os.makedirs(fonts_dir, exist_ok=True)
    os.makedirs(os.path.dirname(css_path), exist_ok=True)

    print(f'Fetching {FONT_URL}')
    css_text = fetch(FONT_URL).decode('utf-8')

    # Split into per-subset blocks; keep only /* latin */ ones.
    blocks = re.split(r'(?=/\* [a-z-]+ \*/)', css_text)
    latin_blocks = [b for b in blocks if b.lstrip().startswith('/* latin */')]
    if not latin_blocks:
        print('ERROR: no latin @font-face rules found — Google may have changed format', file=sys.stderr)
        return 1

    print(f'Found {len(latin_blocks)} latin variants')

    out_css = [
        '/* Self-hosted Google Fonts (latin subset).',
        ' * Generated by tools/fetch-fonts.py — re-run via `make fonts`.',
        ' * Original source: https://fonts.googleapis.com/css2 (SIL OFL 1.1).',
        ' *',
        ' * font-display:optional matches the theme\'s previous remote-font',
        ' * strategy: if the font isn\'t cached and ready within ~100ms,',
        ' * fall back to the system font for this page-load to avoid layout',
        ' * shift. Self-hosting means same-origin + small files, so the',
        ' * fonts almost always arrive within that window after first visit.',
        ' */',
        '',
    ]

    downloaded = 0
    for block in latin_blocks:
        m = FONT_FACE_RE.search(block)
        if not m:
            continue
        family, style, weight, url, urange = (
            m.group(1), m.group(2), m.group(3), m.group(4), m.group(5).strip()
        )

        suffix = '-italic' if style == 'italic' else ''
        filename = f'{slug(family)}-{weight}{suffix}.woff2'
        local_path = os.path.join(fonts_dir, filename)

        if not os.path.exists(local_path):
            with open(local_path, 'wb') as out:
                out.write(fetch(url))
            print(f'  downloaded: {filename} ({os.path.getsize(local_path):,} bytes)')
            downloaded += 1
        else:
            print(f'  exists:     {filename}')

        out_css.extend([
            '@font-face {',
            f"  font-family: '{family}';",
            f'  font-style: {style};',
            f'  font-weight: {weight};',
            '  font-display: optional;',
            f"  src: url('../fonts/{filename}') format('woff2');",
            f'  unicode-range: {urange};',
            '}',
            '',
        ])

    with open(css_path, 'w') as f:
        f.write('\n'.join(out_css))

    print(f'\nWrote {css_path}')
    print(f'New downloads: {downloaded}; cached: {len(latin_blocks) - downloaded}')
    return 0


if __name__ == '__main__':
    # Default theme root is the directory containing the Makefile that
    # invokes us — i.e. cwd. Override by passing a path as $1.
    root = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    sys.exit(main(root))
